import { Geist, Work_Sans } from "next/font/google";
import "./globals.css";
import 'fomantic-ui-css/semantic.min.css';
import { ToastContainer } from "react-toastify";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased  ${workSans.variable} `}
      >
        {children}
              <ToastContainer position="top-center" autoClose={3000} />
        
      </body>
    </html>
  );
}
